name: Database Linting

on:
  pull_request:
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install 

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase and run linting
        run: yarn test:actions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
